### ISSUE TITLE
Theme not working with latest ttrss (v17.12) - not a version bumping issue

### ISSUE THREAD

**Issue by cataldoc** [levito/tt-rss-feedly-theme#51]
Hello

it seems that the theme is not working anymore with ttrss 17.12.
I already bumped the version in the css file but when I select this theme I can only see a blank page and ttrss is unusable.

**Comment by Gravemind** [comment]
I got it kind of useable again with the quickest and dirtiest patch I could see:
- open `feedly.css`
- replace all the occurences of `#ttrssPrefs` by `.ttrss_prefs`
- add this at the end of the file:
```css
body.ttrss_main,
body.ttrss_prefs,
#main {
  position : absolute;
  width: 100%;
  height: 100%;
  border: 0;
  padding: 0;
  margin: 0;
}
```
It's really **not a good fix, there are still issues**, there is a lot more changes than that to be ported to the feedly theme ( `git diff 7c4d7bce3f -- css/` ), but I couldn't go back to the default theme, so that might also help some people until a proper fix.
